### PR TITLE
Add static check and fix all errors

### LINKED ISSUE #155: all: Stricter Golint check.
We currently have [a lint check in the Makefile](https://github.com/open-telemetry/opentelemetry-service/blob/4c7c3ca57110c32803b56cec3fe4733afd74c952/Makefile#L70-L79). However this check is not very strict, for example it doesn't check package documentations. This has caused a bit trouble when we tried to use the otel-svc code when a stricter lint check is enforced. Consider doing a stricter Golint check in the CI.

### PR DESCRIPTION
**Pull request by songy23**
Fixes #155.

This is inspired by [googleapis/google-cloud-go](https://github.com/googleapis/google-cloud-go/blob/fb3c527ecb61102c3e756ad0638abb5ddc40cf6d/internal/kokoro/vet.sh#L72-L104).

### CODE REVIEW

**Comment by songy23** [comment]
I'm still hesitant about adding this check. IMO most suggestions from this tool are kind of nitpicking. For example here's a sample output:
```bash
$ make staticcheck
staticcheck ./...
config/config.go:179:44: should use make(configmodels.Receivers) instead (S1019)
config/config.go:245:44: should use make(configmodels.Exporters) instead (S1019)
config/config.go:302:46: should use make(configmodels.Processors) instead (S1019)
config/config.go:359:44: should use make(configmodels.Pipelines) instead (S1019)
exporter/exporterhelper/metricshelper_test.go:97:68: should use make([]*metricspb.Metric, 1) instead (S1019)
exporter/exporterhelper/tracehelper_test.go:135:33: should use make([]*tracepb.Span, 2) instead (S1019)
exporter/exporterhelper/tracehelper_test.go:154:60: should use make([]*tracepb.Span, 1) instead (S1019)
exporter/exportertest/nop_exporter_test.go:34:5: don't use Yoda conditions (ST1017)
exporter/exportertest/nop_exporter_test.go:48:5: don't use Yoda conditions (ST1017)
exporter/exportertest/nop_exporter_test.go:61:5: don't use Yoda conditions (ST1017)
exporter/exportertest/nop_exporter_test.go:75:5: don't use Yoda conditions (ST1017)
exporter/exportertest/sink_exporter_test.go:42:5: don't use Yoda conditions (ST1017)
exporter/exportertest/sink_exporter_test.go:63:5: don't use Yoda conditions (ST1017)
exporter/jaegerexporter/jaeger_thrift_http_sender.go:114:20: error strings should not be capitalized (ST1005)
exporter/loggingexporter/logging_exporter_test.go:37:5: don't use Yoda conditions (ST1017)
exporter/loggingexporter/logging_exporter_test.go:53:5: don't use Yoda conditions (ST1017)
exporter/opencensusexporter/opencensus.go:60:2: field counter is unused (U1000)
exporter/prometheusexporter/factory_test.go:44:8: const defaultTestEndPoint is unused (U1000)
exporter/zipkinexporter/zipkin.go:110:35: error strings should not be capitalized (ST1005)
internal/collector/processor/idbatcher/id_batcher.go:70:2: field numBatches is unused (U1000)
internal/collector/processor/idbatcher/id_batcher.go:131:3: the surrounding loop is unconditionally terminated (SA4004)
internal/collector/processor/idbatcher/id_batcher_test.go:99:2: the goroutine calls T.Fatal, which must be called in the same goroutine as the test (SA2002)
internal/collector/processor/idbatcher/id_batcher_test.go:111:5: ineffective break statement. Did you mean to break out of the outer loop? (SA4011)
internal/collector/processor/idbatcher/id_batcher_test.go:157:24: should use make([][]byte, numIds) instead (S1019)
internal/collector/processor/metrics.go:58:3: redundant break statement (S1023)
observability/observabilitytest/observabilitytest.go:93:20: error strings should not be capitalized (ST1005)
observability/observabilitytest/observabilitytest.go:102:22: error strings should not be capitalized (ST1005)
observability/observabilitytest/observabilitytest.go:108:19: error strings should not be capitalized (ST1005)
processor/addattributesprocessor/addattributesprocessor.go:30:33: error strings should not be capitalized (ST1005)
processor/attributekeyprocessor/attributekeyprocessor_test.go:161:34: should use make([]*tracepb.Span, 1) instead (S1019)
processor/attributekeyprocessor/attributekeyprocessor_test.go:165:35: should use make([]*tracepb.Span, 1) instead (S1019)
processor/attributekeyprocessor/config_test.go:30:27: this value of err is never used (SA4006)
processor/attributekeyprocessor/config_test.go:78:27: this value of err is never used (SA4006)
processor/attributekeyprocessor/factory.go:47:43: should use make(map[string]NewKeyProperties) instead (S1019)
processor/nodebatcher/node_batcher.go:75:2: field bucketMu is unused (U1000)
processor/probabilisticsampler/config_test.go:56:27: this value of err is never used (SA4006)
processor/tailsampling/processor.go:72:2: const sourceFormat is unused (U1000)
processor/tailsampling/processor.go:204:49: should use make([]sampling.Decision, lenPolicies) instead (S1019)
processor/tailsampling/processor_test.go:216:29: should use make([][]byte, numIds) instead (S1019)
processor/tailsampling/processor_test.go:244:6: func newTestPolicy is unused (U1000)
receiver/jaegerreceiver/trace_receiver.go:74:2: field agentServer is unused (U1000)
receiver/jaegerreceiver/trace_receiver.go:96:2: const defaultZipkinThriftUDPPort is unused (U1000)
receiver/jaegerreceiver/trace_receiver_test.go:108:8: this value of err is never used (SA4006)
receiver/jaegerreceiver/trace_receiver_test.go:109:2: should check returned error before deferring conn.Close() (SA5001)
receiver/opencensusreceiver/octrace/opencensus.go:157:2: field tes is unused (U1000)
receiver/opencensusreceiver/opencensus.go:79:25: error strings should not be capitalized (ST1005)
receiver/opencensusreceiver/options.go:98:2: redundant return statement (S1023)
receiver/prometheusreceiver/internal/metricsbuilder.go:55:2: field ts is unused (U1000)
receiver/prometheusreceiver/internal/metricsbuilder_test.go:201:3: field processErr is unused (U1000)
receiver/prometheusreceiver/metrics_receiver.go:50:2: field ocaStore is unused (U1000)
receiver/prometheusreceiver/metrics_receiver.go:60:2: var errAlreadyStarted is unused (U1000)
receiver/prometheusreceiver/metrics_receiver.go:61:2: var errNilMetricsReceiverSink is unused (U1000)
receiver/vmmetricsreceiver/metrics_receiver.go:27:2: var errNilMetricsConsumer is unused (U1000)
receiver/zipkinreceiver/trace_receiver.go:341:9: this value of err is never used (SA4006)
receiver/zipkinreceiver/trace_receiver_test.go:128:3: field want is unused (U1000)
service/builder/pipelines_builder_test.go:71:16: this value of err is never used (SA4006)
service/builder/pipelines_builder_test.go:142:13: this value of err is never used (SA4006)
service/builder/receivers_builder_test.go:105:16: this value of err is never used (SA4006)
service/builder/receivers_builder_test.go:106:22: this value of err is never used (SA4006)
service/builder/receivers_builder_test.go:222:16: this value of err is never used (SA4006)
service/builder/receivers_builder_test.go:223:22: this value of err is never used (SA4006)
service/service.go:48:2: field processor is unused (U1000)
service/service.go:49:2: field receivers is unused (U1000)
service/service.go:195:25: func (*Application).shutdownReceivers is unused (U1000)
service/service_test.go:54:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
service/service_test.go:96:30: should use make([]string, numAddresses) instead (S1019)
translator/trace/jaeger/constants.go:38:2: var errNilTraceID is unused (U1000)
translator/trace/jaeger/constants.go:39:2: var errWrongLenTraceID is unused (U1000)
translator/trace/jaeger/constants.go:41:2: var errNilID is unused (U1000)
translator/trace/jaeger/constants.go:42:2: var errWrongLenID is unused (U1000)
translator/trace/jaeger/jaegerthrift_to_protospan_test.go:109:8: const numOfFiles is unused (U1000)
translator/trace/jaeger/protospan_to_jaegerproto.go:458:12: this value of err is never used (SA4006)
translator/trace/jaeger/protospan_to_jaegerproto.go:466:26: error strings should not be capitalized (ST1005)
translator/trace/jaeger/protospan_to_jaegerthrift.go:165:26: error strings should not be capitalized (ST1005)
make: *** [staticcheck] Error 1
```

The `strictcheck` tool doesn't provide an auto-fix option. It seems trivial to fix all these errors. However on the other hand Google-Cloud-Go and gRPC-Go both enforces this check. 

A few alternatives I can think of here: 
- Include this check, print the output but don't make it required. 
- Only check a few rules. See gRPC-Go [vet.sh](https://github.com/grpc/grpc-go/blob/24b2fb8959201be9ce659bc87b0d590a34c67eae/vet.sh#L107-L133).

WDYT?

**Comment by songy23** [comment]
Also cc @odeke-em @rghetia.

**Comment by rghetia** [comment]
It may appear annoying at first, especially because you have lots of nitpicks when you run it for the first time. But subsequently there may be fewer errors to fix on incremental changes. Ideally it would have been nice if it also auto corrected. May be there will be such option in future.

**Comment by pjanotti** [comment]
I like the idea, I'm just not sure if we should do it before milestone 0.1.0 or not.

**Comment by songy23** [comment]
IMO this shouldn't be a blocker for v0.1.0 release because it's only affecting code styles rather than functionality.

**Comment by pjanotti** [comment]
Agreed: it isn't a blocker, I'm just worried about the churn. That said if the fixes are all small/nit changes than it is fine.

**Comment by songy23** [comment]
Should all be fixed - PTAL. Hopefully the bug fixing is an one-off effort. In the future new code will conform to the checks.

File: internal/collector/processor/idbatcher/id_batcher.go [hunk 1]
```diff
@@ -120,7 +119,7 @@ func (b *batcher) AddToCurrentBatch(id ID) {
 }
 
 func (b *batcher) CloseCurrentAndTakeFirstBatch() (Batch, bool) {
-	for readBatch := range b.batches {
+	if readBatch, ok := <-b.batches; ok {
```
Comment (tigrannajaryan) [inline internal/collector/processor/idbatcher/id_batcher.go]: Was it intended to change the `for` by `if`?

Comment (songy23) [reply internal/collector/processor/idbatcher/id_batcher.go]: Yes, otherwise either test or static check would fail. The updated code is equivalent to the previous one.

**Comment by songy23** [comment]
Should be ready to merge now.
